server:
  port: 8030
  error:
    include-stacktrace: always

spring:
  data:
    mongodb:
      database: soschitaika
      uri: mongodb://localhost

management:
  endpoints:
    web:
      exposure:
        include: metrics,health
  endpoint:
    health:
      show-details: always

logging:
  level:
    ROOT: INFO
    org.springframework: INFO
