server:
  port: 8030
  error:
    include-stacktrace: always

spring:
  rabbitmq:
    host: 172.17.0.7
    port: 5672
    username: guest
    password: guest
    virtual-host: /
  data:
    mongodb:
      database: soschitaika
      uri: mongodb://localhost
  security:
    oauth2:
      client:
        registration:
          expression-client-oidc:
            provider: spring
            client-id: expression-client
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://game-server:8030/login/oauth2/code/{registrationId}"
            scope: openid,expression.read
            client-name: expression-client-oidc
        provider:
          spring:
            issuer-uri: http://auth-server:9000

expression-server:
  url: http://127.0.0.1:8031

management:
  endpoints:
    web:
      exposure:
        include: metrics,health
  endpoint:
    health:
      show-details: always

logging:
  level:
    ROOT: INFO
    org.springframework: INFO
    org.springframework.security.oauth2: INFO
    org.springframework.integration: INFO
    org.springframework.web.socket: INFO

