server:
  port: 8030
  error:
    include-stacktrace: always

spring:
  data:
    mongodb:
      database: soschitaika
      uri: mongodb://localhost
  security:
    oauth2:
      client:
        registration:
          messaging-client-oidc:
            provider: spring
            client-id: messaging-client
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://192.168.1.139:8030/login/oauth2/code/{registrationId}"
            scope: openid,message.read
            client-name: messaging-client-oidc
        provider:
          spring:
            issuer-uri: http://auth-server:9000

expression:
  base-uri: http://127.0.0.1:8031

management:
  endpoints:
    web:
      exposure:
        include: metrics,health
  endpoint:
    health:
      show-details: always

logging:
  level:
    ROOT: DEBUG
    org.springframework: DEBUG
    org.springframework.security.oauth2: DEBUG

