server:
  port: 8032
  error:
    include-stacktrace: always

management:
  endpoints:
    web:
      exposure:
        include: metrics,health,logfile
  endpoint:
    health:
      show-details: always

jasper:
  template: reportTemplates/gameReport.jrxml

logging:
  level:
    ROOT: INFO
    org.springframework: INFO
