server:
  port: 8032
  error:
    include-stacktrace: always

spring:
  rabbitmq:
    host: 172.17.0.7
    port: 5672
    username: guest
    password: guest
    virtual-host: /

management:
  endpoints:
    web:
      exposure:
        include: metrics,health,logfile
  endpoint:
    health:
      show-details: always

jasper:
  template: reportTemplates/gameReport.jrxml

logging:
  level:
    ROOT: DEBUG
    org.springframework: DEBUG
    org.springframework.integration: DEBUG
    org.springframework.web.socket: DEBUG
