server:
  port: 8081
  error:
    include-stacktrace: always


management:
  endpoints:
    web:
      exposure:
        include: metrics,health,logfile
  endpoint:
    health:
      show-details: always

logging:
  level:
    ROOT: INFO
    org.springframework: INFO
